# Generated by Django 3.1.5 on 2021-01-14 21:19

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(unique=True, verbose_name='высота блока')),
                ('haash', models.CharField(max_length=64, unique=True, verbose_name='хэш блока')),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField(verbose_name='время блока')),
                ('miner', models.CharField(max_length=50, verbose_name='адрес майнера')),
                ('transactionCount', models.PositiveSmallIntegerField(verbose_name='кол-во транзакций')),
            ],
            options={
                'verbose_name_plural': 'блоки',
                'ordering': ('-height',),
            },
        ),
    ]
